### ISSUE TITLE
Suggestion: Add a button that passes all open rubric points with favorite critique.

### ISSUE THREAD

**Issue by WolfgangSteiner** [dylantientcheu/urplus#8]
The existing button passes all rubric points without a comment. It would be nice if we could pass open rubric points with standard praises.

**Comment by michaelhays** [comment]
I'll have to think about this one. I don't want to use the most commonly used remark as the default because that could change unexpectedly without the reviewer noticing. I might change it to order to allow manually assigning a "default", but I'd have to change the database model. That might be what I have to do though.

**Comment by michaelhays** [comment]
I'll have to think about this one. I don't want to set it as the most commonly used passing remark, because that could change without the reviewer noticing. So I'd have to add a field to store the default, which would require updating the model and the UI in a significant way. That's probably what will have to be done, but to be honest I probably won't get around to that anytime soon.
